### ISSUE TITLE
Make PDF File Size Smaller

### ISSUE THREAD

**Issue by jsorge** [there4/markdown-resume#33]
Is there any way to compress the size of the generated PDF output? I'm getting a file that's 1.7MB for a single file, and a few sites I've tried to upload to (Nordstrom, Dice) are rejecting it because their systems can't handle files that large.

Thanks!

**Comment by oflannabhra** [comment]
Just an FYI, this issue persists on OS X, due to an underlying bug in QT (one of wkhtmltopdf's dependencies). Unfortunately for OS X, there is no v0.12 beta to download. The only (apparent) solution until v0.13 is released is to [build from source](http://seankibler.com/installing-wkhtmltopdf-on-mbp-osx-mavericks-109) with a [patched version of QT](http://natepinchot.com/2014/01/31/building-static-wkhtmltopdf/). Both of those linked pages have outdated build instructions, however. I did discover a [binary](https://github.com/yukihr/wkhtmltopdf-0.12.0-build-osx-10.9.1) available for OS X 10.9, but have not tested. If you do decide to build from source, expect to lose 6 hours.
